application:
  name: Java Features
  version: 1.0.0
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  mustache:
    check-template-location: false
  mail:
    host: smtp.ionos.com
    port: 587
    username: support@api-excellence.com
    password: 2Chron7:14!!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
